name: XSD Validation

on:
  push:
#    paths:
#      - '**.xsd'
  pull_request:
    paths:
      - '**.xsd'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Download XSD Schema
        run: |
          echo "XSD=$(curl -s http://www.w3.org/2009/XMLSchema/XMLSchema.xsd)" >> $GITHUB_ENV
      - run: find . -type f -name "*.xsd" -exec xmllint -noout -schema ${{ env.XSD }} {} +
      - run: xmllint -schema ${{ env.XSD }} ./drafts/v2.1/ComicInfo.xsd