name: XSD Validation

on:
  push:
#    paths:
#      - '**.xsd'
  pull_request:
    paths:
      - '**.xsd'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Download XSD Schema
        run: curl -s http://www.w3.org/2009/XMLSchema/XMLSchema.xsd -o XSD-1.1.xsd
      - run: find . -type f -name "*.xsd" -exec xmllint -schema XSD-1.1.xsd {} +
      - run: pwd
      - run: xmllint -schema XSD-1.1.xsd "./drafts/v2.1/ComicInfo.xsd"