name: XSD Validation

on:
  push:
#    paths:
#      - '**.xsd'
  pull_request:
    paths:
      - '**.xsd'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - run: find . -type f -name "*.xsd" -exec xmllint -noout -schema https://www.w3.org/2009/XMLSchema/XMLSchema.xsd {} +
      - run: xmllint -schema https://www.w3.org/2009/XMLSchema/XMLSchema.xsd ./drafts/v2.1/ComicInfo.xsd