name: XSD Validation

on:
  push:
#    paths:
#      - '**.xsd'
  pull_request:
    paths:
      - '**.xsd'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: find . -type f -name "*.xsd" -exec xmllint -noout -schema http://www.w3.org/2009/XMLSchema/XMLSchema.xsd {} +